fix release: on WIN it didn't took .exe, but some metadata... test [cache]

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -9,7 +9,11 @@ permissions:
   contents: write
 
 env:
+  # this overrides vcpkg default and store the cache in common location
   VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg_cache
+  # used for artifacts
+  STAGING_DIR: dist
+  RELEASE_DIR: release_dist
 
 jobs:
   build:
@@ -106,16 +110,32 @@ jobs:
     - name: Prepare Artifacts
       shell: bash
       run: |
-        mkdir -p dist
-        # windows might put is somwhere (not in bin),
-        # also it have .exe which is not on unix
-        find . -type f -name "ssoc*" -not -path "./dist/*" -exec cp {} dist/${{ matrix.artifact_name }} \;
+        mkdir -p "${{ env.STAGING_DIR }}"
+        BIN_NAME="ssoc"
+
+        # Windows specific binary name
+        if [ "${{ runner.os }}" == "Windows" ]; then
+          BIN_NAME="${BIN_NAME}.exe"
+        fi
+
+        # find where the executable is
+        FOUND_PATH=$(find bin -name "$BIN_NAME" -type f \
+          -not -path "*/vcpkg_installed/*" \
+          -not -path "*/${{ env.STAGING_DIR }}/*" \
+          | head -n 1)
+        if [ -z "$FOUND_PATH" ]; then
+          echo "::error::Could not find binary $BIN_NAME in build directory"
+          exit 1
+        fi
+
+        # move it to destination
+        cp "$FOUND_PATH" "${{ env.STAGING_DIR }}/${{ matrix.artifact_name }}"
 
     - name: Upload Artifact
       uses: actions/upload-artifact@v4
       with:
-        name: binary-${{ matrix.os }}
-        path: dist/*
+        name: ssoc-${{ matrix.artifact_name }}
+        path: ${{ env.STAGING_DIR }}/*
         if-no-files-found: error
 
   release:
@@ -130,13 +150,13 @@ jobs:
     - name: Download Artifacts
       uses: actions/download-artifact@v4
       with:
-        pattern: binary-*
-        path: release_dist
+        pattern: ssoc-*
+        path: ${{ env.RELEASE_DIR }}
         merge-multiple: true
 
     - name: Publish Draft Release
       uses: softprops/action-gh-release@v2
       with:
-        files: release_dist/*
+        files: ${{ env.RELEASE_DIR }}/*
         draft: true
         generate_release_notes: false
